name = "scommerce"
compatibility_date = "2026-04-26"

compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "scommerce-db"
database_id = "fccab55b-37e3-4544-aacd-9095df3e9ab3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "scommerce-uploads"

[[kv_namespaces]]
binding = "KV"
id = "88d9b0d91f674eeab798ba907b15c716"

[observability]
enabled = true
