'use client'

import { useEffect } from 'react'

/**
 * Service Worker Handler Component
 *
 * This component handles service worker registration for the PWA.
 * The service worker is automatically generated by @ducanh2912/next-pwa.
 *
 * Note: Service worker is currently disabled due to transpilation issues.
 * Enable when the build configuration is fixed.
 */
export function ServiceWorkerHandler() {
  useEffect(() => {
    // Disable service worker completely due to transpilation issues
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      navigator.serviceWorker.getRegistrations().then((registrations) => {
        registrations.forEach((registration) => {
          registration.unregister()
          console.log('Service Worker unregistered (disabled due to transpilation issues)')
        })
      }).catch((error) => {
        console.log('No service workers to unregister:', error)
      })
    }
  }, [])

  return null
}

// Show a subtle update notification
function showUpdatePrompt() {
  // Disabled - service worker not in use
  if (typeof window === 'undefined') return
}
