'use client'

import { useEffect, useState, useRef } from 'react'
import { Download, X, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'

/**
 * Service Worker Handler Component
 *
 * This component handles service worker registration for the PWA.
 * The service worker is automatically generated by @ducanh2912/next-pwa.
 *
 * Features:
 * - Non-intrusive update notifications
 * - Preserves scroll position during updates
 * - Allows users to delay updates
 */
export function ServiceWorkerHandler() {
  const [waitingServiceWorker, setWaitingServiceWorker] = useState<ServiceWorker | null>(null)
  const [showUpdatePrompt, setShowUpdatePrompt] = useState(false)
  const [isUpdating, setIsUpdating] = useState(false)
  const hasShownPrompt = useRef(false)

  useEffect(() => {
    // Store scroll position before any potential reload
    const saveScrollPosition = () => {
      if (typeof window !== 'undefined') {
        sessionStorage.setItem('scrollPosition', window.scrollY.toString())
        sessionStorage.setItem('scrollPath', window.location.pathname)
      }
    }

    // Restore scroll position after page load
    const restoreScrollPosition = () => {
      if (typeof window !== 'undefined') {
        const savedPath = sessionStorage.getItem('scrollPath')
        const savedPosition = sessionStorage.getItem('scrollPosition')
        
        // Only restore if we're on the same page
        if (savedPath === window.location.pathname && savedPosition) {
          window.scrollTo(0, parseInt(savedPosition, 10))
          sessionStorage.removeItem('scrollPosition')
          sessionStorage.removeItem('scrollPath')
        }
      }
    }

    // Save scroll position periodically and on scroll
    const handleScroll = () => {
      if (typeof window !== 'undefined') {
        sessionStorage.setItem('scrollPosition', window.scrollY.toString())
        sessionStorage.setItem('scrollPath', window.location.pathname)
      }
    }

    // Restore scroll position on initial load
    restoreScrollPosition()

    // Listen for scroll events to save position
    window.addEventListener('scroll', handleScroll, { passive: true })

    // Save position before unload
    window.addEventListener('beforeunload', saveScrollPosition)

    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      // Register the service worker
      navigator.serviceWorker
        .register('/sw.js', {
          scope: '/'
        })
        .then((registration) => {
          console.log('Service Worker registered successfully:', registration.scope)

          // Check for updates periodically
          const checkForUpdates = () => {
            registration.update()
          }

          // Check for updates every hour (3600000 ms)
          const updateInterval = setInterval(checkForUpdates, 3600000)

          // Check for updates immediately on registration
          registration.update()

          // Listen for updates
          registration.addEventListener('updatefound', () => {
            const newWorker = registration.installing
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  // New content is available; show update prompt
                  if (!hasShownPrompt.current) {
                    setWaitingServiceWorker(newWorker)
                    setShowUpdatePrompt(true)
                    hasShownPrompt.current = true
                  }
                }
              })
            }
          })

          return () => {
            clearInterval(updateInterval)
          }
        })
        .catch((error) => {
          console.error('Service Worker registration failed:', error)
        })

      // Listen for controlling service worker changes
      // We DON'T auto-reload here anymore - let the user control when to update
      navigator.serviceWorker.addEventListener('controllerchange', () => {
        // Save current scroll position before reload
        saveScrollPosition()
        // Delay reload slightly to ensure new content is ready
        setTimeout(() => {
          window.location.reload()
        }, 100)
      })
    }

    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('beforeunload', saveScrollPosition)
    }
  }, [])

  // Function to activate the waiting service worker
  const activateUpdate = () => {
    if (waitingServiceWorker) {
      setIsUpdating(true)
      // Save scroll position before update
      if (typeof window !== 'undefined') {
        sessionStorage.setItem('scrollPosition', window.scrollY.toString())
        sessionStorage.setItem('scrollPath', window.location.pathname)
      }
      // Tell the service worker to skip waiting and activate
      waitingServiceWorker.postMessage({ type: 'SKIP_WAITING' })
      setShowUpdatePrompt(false)
    }
  }

  // Function to dismiss the update prompt and remind later
  const dismissUpdate = () => {
    setShowUpdatePrompt(false)
    // Reset the flag so we can show the prompt again in an hour
    setTimeout(() => {
      hasShownPrompt.current = false
    }, 3600000) // 1 hour
  }

  return (
    <>
      {showUpdatePrompt && (
        <div className="fixed bottom-4 right-4 z-50 max-w-sm animate-in slide-in-from-bottom-4 fade-in duration-300">
          <div className="rounded-lg border bg-background p-4 shadow-lg">
            <div className="mb-3 flex items-start gap-3">
              <div className="flex-shrink-0">
                <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center">
                  {isUpdating ? (
                    <RefreshCw className="h-5 w-5 text-primary animate-spin" />
                  ) : (
                    <Download className="h-5 w-5 text-primary" />
                  )}
                </div>
              </div>
              <div className="flex-1">
                <h4 className="font-semibold text-sm">Update Available</h4>
                <p className="text-sm text-muted-foreground mt-1">
                  {isUpdating 
                    ? 'Applying update... Your page will refresh momentarily.'
                    : 'A new version is available. Update to get the latest features and improvements.'}
                </p>
              </div>
              <button
                onClick={dismissUpdate}
                className="flex-shrink-0 text-muted-foreground hover:text-foreground transition-colors"
                disabled={isUpdating}
              >
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="flex gap-2">
              <button
                onClick={activateUpdate}
                disabled={isUpdating}
                className="inline-flex h-9 flex-1 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                {isUpdating ? 'Updating...' : 'Update Now'}
              </button>
              <button
                onClick={dismissUpdate}
                disabled={isUpdating}
                className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                Later
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
