'use client'

import { useEffect, useState } from 'react'

/**
 * Service Worker Handler Component
 *
 * This component handles service worker registration for the PWA.
 * The service worker is automatically generated by @ducanh2912/next-pwa.
 */
export function ServiceWorkerHandler() {
  const [waitingServiceWorker, setWaitingServiceWorker] = useState<ServiceWorker | null>(null)
  const [showUpdatePrompt, setShowUpdatePrompt] = useState(false)

  useEffect(() => {
    if (typeof window !== 'undefined' && 'serviceWorker' in navigator) {
      // Register the service worker
      navigator.serviceWorker
        .register('/sw.js', {
          scope: '/'
        })
        .then((registration) => {
          console.log('Service Worker registered successfully:', registration.scope)

          // Check for updates
          registration.addEventListener('updatefound', () => {
            const newWorker = registration.installing
            if (newWorker) {
              newWorker.addEventListener('statechange', () => {
                if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
                  // New content is available; show update prompt
                  setWaitingServiceWorker(newWorker)
                  setShowUpdatePrompt(true)
                }
              })
            }
          })
        })
        .catch((error) => {
          console.error('Service Worker registration failed:', error)
        })

      // Listen for controlling service worker changes
      navigator.serviceWorker.addEventListener('controllerchange', () => {
        // When the new service worker takes control, reload the page
        window.location.reload()
      })
    }
  }, [])

  // Function to activate the waiting service worker
  const activateUpdate = () => {
    if (waitingServiceWorker) {
      waitingServiceWorker.postMessage({ type: 'SKIP_WAITING' })
    }
    setShowUpdatePrompt(false)
  }

  // Function to dismiss the update prompt
  const dismissUpdate = () => {
    setShowUpdatePrompt(false)
  }

  return (
    <>
      {showUpdatePrompt && (
        <div className="fixed bottom-4 right-4 z-50 max-w-sm animate-in slide-in-from-bottom-4">
          <div className="rounded-lg border bg-background p-4 shadow-lg">
            <div className="mb-3">
              <h4 className="font-semibold text-sm">Update Available</h4>
              <p className="text-sm text-muted-foreground">
                A new version of the app is available. Would you like to update?
              </p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={activateUpdate}
                className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                Update Now
              </button>
              <button
                onClick={dismissUpdate}
                className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                Later
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}

// Show a subtle update notification
function showUpdatePrompt() {
  if (typeof window === 'undefined') return
  // This function is now integrated into the component
}
